data:
  cols:
    bis: "BIS/BIS"
    sqi: "BIS/SQI"
    emg: "BIS/EMG"
    eeg: ["BIS/EEG1_WAV", "BIS/EEG2_WAV"]
    vital: ["Solar8000/ART_SBP","Solar8000/ART_DBP","Solar8000/PLETH_HR","Solar8000/RR_CO2","Solar8000/BT"]
    drug: ["Orchestra/PPF20_RATE"]
prepare:
  io:
    output_dir: "data/processed/v1"
  id:
    cids: []
    n_cases: 100
  runtime:
    verbose: true
    save_npz: true
    save_parquet: false
  params:
    fs: 128.0
    
    treat_zero_as_nan: true
    add_sec_col: true
    reset_row_index: false

    window_sec: 4
    bands: ((0.5, 4, "delta"), (4, 8, "theta"), (8, 13, "alpha"), (13, 30, "beta"), (30, 47, "gamma"))
    main_band: (0.5, 47.0)
    use_relative: true
    use_log: true
    min_coverage: 0.8
    eps: 1e-12

    bis_ffill_seconds: 1
    sqi_threshold: 50
    lag_seconds: 15